language: php
php:
  - '5.6'
before_script:
  - cd ..
  - wget https://github.com/wikimedia/mediawiki/archive/1.25.5.tar.gz
  - tar -zxf 1.25.5.tar.gz
  - mv mediawiki-1.25.5 wiki
  - cd wiki
  - mysql -e 'create database wiki;'
  - git clone -b REL1_25 https://gerrit.wikimedia.org/r/p/mediawiki/vendor.git
  - php maintenance/install.php --dbtype mysql --dbuser root --dbname wiki --dbpath $TRAVIS_BUILD_DIR --pass nyan TravisWiki admin
  - cd extensions
  - cp -r $TRAVIS_BUILD_DIR Mustache_i18n
  - cd ..
  - composer install --no-dev
script:
  - php tests/phpunit/phpunit.php extensions/Mustache_i18n/tests/phpunit/